name: Release as AWS Lambda artefact

on:
  push:
    branches: [ "LOG-223" ]

jobs:
  deployment:
    environment: production

    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      packages: write
      deployments: write

    env:
      VERSION: "0.0.${{ github.run_number }}-${{ github.run_attempt }}"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Lambda Artefact
        run: zip brontobytes-aws-ingestion-python log_forwarder/*
        shell: bash

      - name: Tag & Commit Artefact
        run: git add brontobytes-aws-ingestion-python.zip; git commit -m 'adding new artefact'
      - name: Create git tag
        run: git tag ${{ env.VERSION }}
      - name: Push git tag
        run: git push origin ${{ env.VERSION }}
