name: Test Package

on:
  pull_request:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: write
  packages: write
  deployments: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Test
        run: ./test.sh
